// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBqaDZwS3eOEGSiUlcvVyh2_sma39otzs',
    appId: '1:1067315628598:web:929d6e0c1e305a7c5da697',
    messagingSenderId: '1067315628598',
    projectId: 'finance4u-app-v1',
    authDomain: 'finance4u-app-v1.firebaseapp.com',
    storageBucket: 'finance4u-app-v1.firebasestorage.app',
    measurementId: 'G-8KCZJJQMVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9l-oj1aVmiBbGWZrZZvrni0TZhKWQ2Nc',
    appId: '1:1067315628598:android:7ab1dfc3cad39e715da697',
    messagingSenderId: '1067315628598',
    projectId: 'finance4u-app-v1',
    storageBucket: 'finance4u-app-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_gfNlcWnnYZ-KmHRXG-bwGidCyR5GL2c',
    appId: '1:1067315628598:ios:1ec1a7c2f60b1a005da697',
    messagingSenderId: '1067315628598',
    projectId: 'finance4u-app-v1',
    storageBucket: 'finance4u-app-v1.firebasestorage.app',
    iosClientId: '1067315628598-aem15q96uc80nc0u9rtm30ucb6vnbgc7.apps.googleusercontent.com',
    iosBundleId: 'com.example.duolingoFinanzas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_gfNlcWnnYZ-KmHRXG-bwGidCyR5GL2c',
    appId: '1:1067315628598:ios:1ec1a7c2f60b1a005da697',
    messagingSenderId: '1067315628598',
    projectId: 'finance4u-app-v1',
    storageBucket: 'finance4u-app-v1.firebasestorage.app',
    iosClientId: '1067315628598-aem15q96uc80nc0u9rtm30ucb6vnbgc7.apps.googleusercontent.com',
    iosBundleId: 'com.example.duolingoFinanzas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBqaDZwS3eOEGSiUlcvVyh2_sma39otzs',
    appId: '1:1067315628598:web:397a12fb5c808a1d5da697',
    messagingSenderId: '1067315628598',
    projectId: 'finance4u-app-v1',
    authDomain: 'finance4u-app-v1.firebaseapp.com',
    storageBucket: 'finance4u-app-v1.firebasestorage.app',
    measurementId: 'G-P4QC4K4N2K',
  );
}
