#!/usr/bin/env python3
"""Generate lib/data/pill_quiz_extras.dart with 7 questions per pill."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "lib" / "data" / "pill_quiz_extras.dart"

# Each entry: (question, [opt0, opt1, opt2, opt3], correctIndex)
PILLS = {
    "Regla 50/30/20": [
        ("¿Qué porcentaje de ingresos destina la regla a deseos y ocio?",
         ["10%", "20%", "30%", "50%"], 2),
        ("Si cobras 1.600€ netos al mes, ¿cuánto destinarías a necesidades básicas?",
         ["480€", "640€", "800€", "960€"], 2),
        ("¿Qué hacer si tus gastos fijos superan el 50% de ingresos?",
         ["Ignorarlo", "Revisar y reducir gastos fijos", "Pedir más crédito", "Dejar de ahorrar"], 1),
        ("¿Qué error compromete la regla 50/30/20?",
         ["Automatizar el ahorro", "Usar el ahorro para gastos no urgentes", "Revisar el presupuesto", "Separar cuentas"], 1),
        ("Con ingresos variables, ¿sobre qué base conviene aplicar la regla?",
         ["El mejor mes del año", "El ingreso medio reciente", "Solo la nómina base", "Los ingresos brutos"], 1),
        ("¿Cuál de estos NO es un bloque de la regla 50/30/20?",
         ["Necesidades", "Deseos", "Ahorro e inversión", "Impuestos directos"], 3),
        ("¿Por qué automatizar el 20% de ahorro?",
         ["Evita pagar IVA", "Crea el hábito antes de gastar", "Sube el salario", "Elimina deudas"], 1),
    ],
    "Fondo de emergencia": [
        ("¿Qué gastos deben cubrir los meses del fondo de emergencia?",
         ["Vacaciones y ocio", "Gastos básicos esenciales", "Inversiones en bolsa", "Compras de lujo"], 1),
        ("¿Por qué no conviene invertir el fondo de emergencia en bolsa?",
         ["No genera rentabilidad", "Riesgo y falta de liquidez inmediata", "Es ilegal", "Paga más impuestos"], 1),
        ("¿Con qué frecuencia revisar el fondo de emergencia?",
         ["Nunca", "Al menos una vez al año", "Cada década", "Solo al jubilarte"], 1),
        ("¿Para qué NO deberías usar el fondo de emergencia?",
         ["Avería del coche", "Vacaciones planificadas", "Pérdida de empleo", "Reparación urgente"], 1),
        ("Si tus gastos básicos son 900€/mes, ¿cuánto mínimo recomiendan (3 meses)?",
         ["900€", "1.800€", "2.700€", "9.000€"], 2),
        ("¿Por qué evitar guardar el fondo en efectivo en casa?",
         ["No genera intereses", "Riesgo de robo o incendio", "El banco lo prohíbe", "Pierdes la nómina"], 1),
        ("Si solo puedes ahorrar 20€ al mes, ¿qué hacer?",
         ["Esperar a ganar más", "Empezar igualmente poco a poco", "Pedir un préstamo", "No crear fondo"], 1),
    ],
    "Ahorro automático": [
        ("¿Qué bancos españoles permiten transferencias automáticas?",
         ["Ninguno", "La mayoría de bancos tradicionales y online", "Solo el Banco de España", "Solo cajas rurales"], 1),
        ("¿Por qué ahorrar el día después de cobrar?",
         ["Porque el banco lo exige", "Antes de que el dinero se gaste", "Para pagar menos IRPF", "Para evitar el IVA"], 1),
        ("¿Qué estrategia complementa bien el ahorro automático?",
         ["Gastar primero y ahorrar lo que sobre", "Cuenta de ahorro separada del día a día", "Usar solo efectivo", "Cancelar seguros"], 1),
        ("¿Qué hacer si al principio no puedes ahorrar mucho?",
         ["No automatizar nada", "Empezar con una cantidad pequeña y subirla", "Pedir crédito", "Esperar a fin de año"], 1),
        ("¿Qué ventaja tienen las cuentas de ahorro online para automatizar?",
         ["Sin comisiones y rentabilidad", "Garantizan doble salario", "Evitan impuestos", "Sin límites legales"], 0),
        ("¿Qué problema evita el ahorro automático?",
         ["La inflación directamente", "Depender solo de la fuerza de voluntad", "Pagar hipoteca", "Cotizar a la Seguridad Social"], 1),
        ("¿Qué NO es una buena práctica con el ahorro automático?",
         ["Programar transferencia periódica", "Ir subiendo la cantidad gradualmente", "Usar la cuenta de ahorro para caprichos", "Revisar el progreso"], 2),
    ],
    "Evita gastos hormiga": [
        ("¿Qué incluyen típicamente los gastos hormiga?",
         ["Hipoteca y alquiler", "Cafés, snacks y suscripciones pequeñas", "Seguro del coche", "IRPF anual"], 1),
        ("¿Qué herramienta ayuda a detectar gastos hormiga?",
         ["Solo la memoria", "Apps o extractos bancarios categorizados", "Redes sociales", "Lotería"], 1),
        ("Si gastas 2€ diarios en snacks laborables (~22 días), ¿cuánto al mes?",
         ["22€", "44€", "66€", "220€"], 1),
        ("¿Qué actitud frena los gastos hormiga?",
         ["Comprar más en rebajas", "Conciencia y registro de pequeños gastos", "Usar más tarjetas", "Pedir préstamos"], 1),
        ("¿Qué error común impide reducir gastos hormiga?",
         ["Revisar movimientos bancarios", "Pensar que 'no importan' por ser pequeños", "Llevar café de casa", "Anotar gastos"], 1),
        ("¿Qué suscripción olvidada suele ser gasto hormiga?",
         ["Hipoteca", "App o streaming no usado", "Seguridad Social", "IBI"], 1),
        ("¿Cuál es el beneficio de reducir gastos hormiga?",
         ["Más capacidad de ahorro real", "Menos impuestos automáticos", "Mejor historial hipotecario directo", "Subida de nómina"], 0),
    ],
    "Reto de 30 días": [
        ("¿Qué variante del reto incrementa el ahorro cada día?",
         ["Ahorrar lo mismo siempre", "1€ día 1, 2€ día 2, etc.", "Gastar menos solo el día 30", "Invertir en bolsa"], 1),
        ("¿Qué herramienta bancaria ayuda a seguir el reto?",
         ["Tarjeta revolving", "Metas o subcuentas de ahorro", "Préstamo personal", "Cuenta de crédito"], 1),
        ("¿Qué error arruina el reto de 30 días?",
         ["Registrar el progreso", "Perder la constancia a mitad", "Compartir el reto", "Empezar con 1€"], 1),
        ("Si ahorras 5€ fijos cada día durante 30 días, ¿cuánto acumulas?",
         ["30€", "75€", "150€", "465€"], 2),
        ("¿Por qué transferir el ahorro al terminar el reto?",
         ["Para pagar impuestos", "Evitar gastarlo impulsivamente", "Por ley bancaria", "Para invertir en FOREX"], 1),
        ("¿Qué beneficio psicológico da el reto?",
         ["Ver resultados rápidos y crear hábito", "Eliminar deudas al instante", "Evitar cotizar", "Subir el Euríbor"], 0),
        ("¿Con quién puede ser útil compartir el reto?",
         ["Solo con el banco", "Amigos o familia para motivación", "Con inversores FOREX", "Con Hacienda"], 1),
    ],
    "¿Qué son los impuestos?": [
        ("¿Qué impuesto grava la propiedad de una vivienda en España?",
         ["IVA", "IBI", "IRPF", "IVA superreducido"], 1),
        ("¿Qué significa que el IRPF es progresivo?",
         ["Todos pagan lo mismo", "A más ingresos, tipos más altos en tramos", "Solo pagan empresas", "Los tipos bajan con el salario"], 1),
        ("¿Qué servicio público NO financia directamente la fiscalidad general?",
         ["Sanidad", "Educación", "Salario privado de empresas", "Pensiones"], 2),
        ("¿Qué impuesto pagan las empresas sobre beneficios?",
         ["IRPF", "Impuesto de Sociedades", "IVA", "IBI"], 1),
        ("¿Qué impuestos especiales existen en España?",
         ["Solo IRPF", "Gasolina, alcohol y tabaco", "Solo IVA", "Ninguno"], 1),
        ("¿Por qué declarar todos los ingresos?",
         ["Es opcional", "Obligación legal y evita sanciones", "Solo si eres autónomo", "Para cobrar paro"], 1),
        ("¿Qué ventaja tiene entender los impuestos?",
         ["Evitar pagarlos", "Planificar mejor las finanzas personales", "No cotizar", "Eliminar el IVA"], 1),
    ],
    "IRPF: El impuesto principal": [
        ("¿Qué es la base imponible del IRPF?",
         ["Solo el salario neto", "Ingresos menos deducciones permitidas", "El IVA pagado", "La hipoteca"], 1),
        ("¿Qué deducción puede reducir tu IRPF?",
         ["Compras de ropa", "Aportaciones a plan de pensiones", "Lotería", "Vacaciones"], 1),
        ("¿Qué ocurre si las retenciones superan lo debido?",
         ["Pierdes el dinero", "Hacienda puede devolverte", "Sube el IVA", "No pasa nada"], 1),
        ("¿Qué ingresos deben incluirse en la declaración?",
         ["Solo nómina", "Salario, alquileres, freelance, etc.", "Solo efectivo", "Solo pensiones"], 1),
        ("¿Para qué sirve un gestor en IRPF complejo?",
         ["Evitar pagar impuestos", "Optimizar y cumplir correctamente", "Eliminar retenciones", "No declarar"], 1),
        ("¿Qué tramo de IRPF aplica a ingresos muy altos (ej. >300.000€)?",
         ["19%", "24%", "47%", "0%"], 2),
        ("¿Qué documentos conviene guardar para deducciones?",
         ["Solo nóminas", "Justificantes de gastos deducibles", "Tickets de ocio", "Recibos de lotería"], 1),
    ],
    "Seguridad Social": [
        ("¿Qué prestación cubre baja por maternidad/paternidad?",
         ["Solo IRPF", "Seguridad Social", "IVA", "IBI"], 1),
        ("¿Quién paga la mayor parte de cotizaciones en un contrato?",
         ["El trabajador solo", "Principalmente la empresa", "El cliente", "Hacienda"], 1),
        ("¿Qué documento revisar para verificar años cotizados?",
         ["DNI", "Informe de vida laboral", "Pasaporte", "Carnet de conducir"], 1),
        ("¿Qué factor influye en el cálculo de la pensión?",
         ["Color del coche", "Años cotizados y base reguladora", "Número de hijos solo", "Tipo de vivienda"], 1),
        ("¿Cómo cotizan los autónomos?",
         ["No cotizan", "Cuotas mensuales según ingresos/base", "Solo en verano", "Una vez al año"], 1),
        ("¿Qué cubre la asistencia sanitaria pública?",
         ["Solo dentistas privados", "Atención médica básica", "Vacaciones", "Seguro de hogar"], 1),
        ("¿Por qué complementar con plan de pensiones privado?",
         ["Es obligatorio", "Complementar pensión pública futura", "Evitar IVA", "No pagar IRPF"], 1),
    ],
    "IVA: El impuesto invisible": [
        ("¿Qué tipo de IVA aplica al transporte público en España?",
         ["4%", "10% reducido", "21% general", "0%"], 1),
        ("Si un producto cuesta 100€ sin IVA al 21%, ¿precio final?",
         ["110€", "121€", "100€", "131€"], 1),
        ("¿Quién puede deducir IVA de sus compras profesionales?",
         ["Cualquier particular", "Autónomos y empresas", "Solo jubilados", "Menores de edad"], 1),
        ("¿Qué estrategia reduce impacto del IVA en consumo?",
         ["Comprar solo productos al 21%", "Priorizar productos con IVA reducido", "No comprar nunca", "Pagar en efectivo siempre"], 1),
        ("¿El precio en tienda ya incluye IVA?",
         ["No, se suma al pagar", "Sí, en la mayoría de casos", "Solo online", "Solo en restauración"], 1),
        ("¿Qué IVA llevan la ropa y tecnología?",
         ["4%", "10%", "21% general", "0%"], 2),
        ("¿Por qué guardar facturas importantes?",
         ["Por moda", "Para deducciones o reclamaciones", "Evitar IRPF", "Cobrar paro"], 1),
    ],
    "Ejemplo completo: ¿Cuánto se lleva el Estado?": [
        ("En el ejemplo de María, ¿qué impuesto se descuenta mensualmente de nómina además de IRPF?",
         ["IBI", "Cotizaciones a Seguridad Social", "ITP", "Impuesto de circulación"], 1),
        ("¿Qué porcentaje aproximado de impuestos sobre bruto muestra el ejemplo?",
         ["10%", "25%", "40% aprox.", "90%"], 2),
        ("¿Qué impuesto anual paga quien tiene vivienda (IBI)?",
         ["Sobre compra", "Sobre propiedad del inmueble", "Sobre salario", "Sobre nómina"], 1),
        ("¿Qué financia el IRPF recaudado?",
         ["Solo empresas privadas", "Gastos públicos del Estado", "Vacaciones de funcionarios", "Solo defensa"], 1),
        ("¿Por qué el IVA es 'invisible' para el consumidor?",
         ["No existe", "Ya va incluido en el precio final", "Solo lo pagan ricos", "Es voluntario"], 1),
        ("¿Qué optimización fiscal menciona el ejemplo?",
         ["No pagar IVA", "Planes de pensiones y deducciones", "Esconder ingresos", "Solo efectivo"], 1),
        ("¿Qué representa el salario neto real en el ejemplo?",
         ["Bruto menos impuestos y cotizaciones", "Solo bruto", "Solo IVA", "Beneficio empresarial"], 0),
    ],
    "¿Qué es invertir?": [
        ("¿Qué riesgo tiene dejar ahorros sin remunerar?",
         ["Ganar demasiado", "Pérdida de poder adquisitivo por inflación", "Pagar más IVA", "Subir IRPF"], 1),
        ("¿Qué hacer antes de invertir?",
         ["Pedir préstamo", "Definir objetivo y horizonte", "Gastar todo", "Solo seguir modas"], 1),
        ("¿Qué NO deberías invertir?",
         ["Dinero para emergencias a corto plazo", "Excedente a largo plazo", "Ahorro para jubilación", "Capital sobrante"], 0),
        ("¿Qué tributan las ganancias de fondos y acciones en España?",
         ["IVA", "IRPF", "IBI", "Ninguno"], 1),
        ("¿Qué error evitar al invertir?",
         ["Diversificar", "Invertir sin entender el producto", "Informarse", "Comparar comisiones"], 1),
        ("¿Qué producto combina ahorro jubilación y ventaja fiscal?",
         ["Cuenta corriente", "Plan de pensiones", "Préstamo personal", "Tarjeta revolving"], 1),
        ("¿Invertir es lo mismo que apostar?",
         ["Sí, idéntico", "No, es estrategia a medio/largo plazo", "Solo en cripto", "Solo en vivienda"], 1),
    ],
    "Diversificación": [
        ("¿Qué problema tiene concentrar todo en vivienda o depósitos?",
         ["Menos impuestos", "Mayor riesgo si ese activo cae", "Más liquidez", "Mejor diversificación"], 1),
        ("¿Con qué frecuencia revisar la cartera diversificada?",
         ["Cada hora", "Al menos una vez al año", "Nunca", "Solo en crisis"], 1),
        ("¿Qué sectores ayudan a diversificar?",
         ["Uno solo siempre", "Renta fija, variable, depósitos, etc.", "Solo cripto", "Solo efectivo"], 1),
        ("¿Qué error de diversificación es común en España?",
         ["Usar fondos", "Concentrar todo en vivienda", "Tener depósitos", "Leer folletos"], 1),
        ("Si tienes 10.000€, ¿qué reparto ilustra diversificación?",
         ["Todo en una acción", "Fondos fijos + variables + depósito", "Todo efectivo", "Solo deuda"], 1),
        ("¿La diversificación elimina todo riesgo?",
         ["Sí, totalmente", "No, pero lo reduce", "Solo en depósitos", "Solo en bonos"], 1),
        ("¿Por qué no invertir solo en lo cómodo?",
         ["Porque es ilegal", "Aumenta concentración de riesgo", "Paga más IVA", "Sube IRPF"], 1),
    ],
    "Riesgo y rentabilidad": [
        ("¿Qué es el riesgo de liquidez?",
         ["Que suba el Euríbor", "No poder vender cuando necesitas sin pérdida", "Robo bancario", "Solo en vivienda"], 1),
        ("¿Hasta cuánto están garantizados depósitos en España?",
         ["10.000€", "50.000€", "100.000€", "Sin límite"], 2),
        ("¿Qué perfil puede asumir más riesgo?",
         ["Joven con horizonte largo", "Prejubilado sin ahorro", "Quien necesita dinero en 1 año", "Sin fondo emergencia"], 0),
        ("¿Qué normativa clasifica riesgo 1-7 en España?",
         ["MiFID europea", "Ley de loterías", "Código civil", "IBI"], 0),
        ("¿Qué producto es riesgo medio-bajo típico?",
         ["Criptomonedas", "Fondos de renta fija", "Acciones emergentes", "Derivados apalancados"], 1),
        ("¿Qué es riesgo de inflación?",
         ["Robo", "Pérdida de poder adquisitivo", "Impago bancario", "Solo en hipotecas"], 1),
        ("¿Qué evalúa el test de perfil inversor?",
         ["Color favorito", "Edad, experiencia, objetivos y tolerancia", "Número de hijos solo", "Marca del móvil"], 1),
    ],
    "Invierte a largo plazo": [
        ("¿Qué ventaja da el interés compuesto a largo plazo?",
         ["Pagar menos IVA", "Reinvertir ganancias que generan más ganancias", "Eliminar comisiones", "Evitar IRPF siempre"], 1),
        ("¿Qué es dollar-cost averaging?",
         ["Vender todo en pánico", "Invertir cantidad fija periódicamente", "Solo comprar en máximos", "Apostar en FOREX"], 1),
        ("¿Por qué no vender en pánico cuando baja el mercado?",
         ["Porque siempre sube mañana", "El tiempo permite recuperación histórica", "Es ilegal vender", "El banco lo prohíbe"], 1),
        ("¿Qué horizonte para fondos de renta variable global?",
         ["1 mes", "10+ años típicamente", "Solo 1 día", "Solo 1 semana"], 1),
        ("¿Qué error con dinero a corto plazo?",
         ["Fondo emergencia líquido", "Invertirlo en productos volátiles de largo plazo", "Depósito", "Cuenta remunerada"], 1),
        ("¿Con qué frecuencia revisar inversiones sin obsesionarse?",
         ["Cada minuto", "Una vez al mes puede bastar", "Nunca mirar", "Solo en Navidad"], 1),
        ("¿Qué aliado es clave según la lección?",
         ["La impulsividad", "El tiempo", "El apalancamiento extremo", "Comprar rumores"], 1),
    ],
    "Fondos de inversión": [
        ("¿Qué son las participaciones de un fondo?",
         ["Acciones de una empresa", "Cuotas proporcionales del patrimonio del fondo", "Bonos del Estado", "Depósitos"], 1),
        ("¿Qué comisión descuenta anualmente del patrimonio?",
         ["Solo suscripción", "Comisión de gestión", "IRPF mensual", "IBI"], 1),
        ("¿Qué ventaja fiscal tienen traspasos entre fondos en España?",
         ["Siempre libres de impuesto al traspasar", "No tributas hasta vender (traspaso diferido)", "Exentos de IRPF para siempre", "Sin comisiones"], 1),
        ("¿Qué fondo replica un índice con bajas comisiones?",
         ["Gestión activa cara", "ETF o fondo indexado pasivo", "Fondo temático único", "Producto estructurado"], 1),
        ("¿Qué leer antes de invertir en un fondo?",
         ["Solo publicidad", "Folleto informativo obligatorio", "Comentarios anónimos", "Nada"], 1),
        ("¿Por qué no elegir solo por rentabilidad pasada?",
         ["Garantiza futuro", "No garantiza rentabilidad futura", "Es ilegal mirar", "Sube comisiones"], 1),
        ("¿Inversión mínima típica en muchos fondos españoles?",
         ["Desde 100€ aprox.", "Solo 1 millón €", "Solo 0€", "50.000€ mínimo"], 0),
    ],
    "Cómo crean dinero los bancos": [
        ("¿Qué tipo de dinero crean principalmente los bancos al prestar?",
         ["Solo billetes", "Depósitos bancarios (dinero scriptural)", "Monedas de oro", "Criptomonedas"], 1),
        ("¿Qué es la reserva fraccionaria?",
         ["Guardar todo en efectivo", "Mantener parte de depósitos y prestar el resto", "No prestar nunca", "Imprimir billetes"], 1),
        ("¿Qué hace el BCE con tipos de interés?",
         ["Fija salarios", "Influye en crédito e inflación", "Cobra IVA", "Emite DNI"], 1),
        ("¿Qué ocurre si muchos retiran depósitos a la vez?",
         ["Banco tiene todo en efectivo", "Solo fracción disponible; existen garantías", "Sube IRPF", "Baja Euríbor automático"], 1),
        ("Crédito barato y abundante suele...",
         ["Reducir siempre precios", "Impulsar economía pero puede inflar", "Eliminar IVA", "Quitar pensiones"], 1),
        ("¿Tu deuda hipotecaria pagada implica...?",
         ["Más dinero circulante", "Ese dinero deja de circular en el sistema", "Sube Euríbor", "Baja IBI"], 1),
        ("¿Qué mito es falso sobre bancos?",
         ["Crean depósitos al prestar", "Solo prestan lo ya depositado por otros", "BCE regula", "Hay garantía depósitos"], 1),
    ],
    "Planes de pensiones": [
        ("¿Cuánto pueden desgravar mayores de 50 años (límite ampliado)?",
         ["500€", "1.500€", "Hasta 2.000€", "Sin límite"], 2),
        ("¿Qué ocurre con beneficios dentro del plan?",
         ["Tributan cada año", "No tributan hasta rescate", "Pagan IVA", "Se pierden"], 1),
        ("¿Qué plan ofrece la empresa al trabajador?",
         ["Plan individual solo", "Plan de empleo", "Plan de lotería", "Ninguno legal"], 1),
        ("¿Qué circunstancia permite rescate anticipado?",
         ["Comprar móvil", "Desempleo larga duración (según normativa)", "Vacaciones", "Capricho"], 1),
        ("¿Qué error con comisiones altas?",
         ["Mejoran rentabilidad neta", "Reducen rentabilidad neta", "Son gratis", "Evitan IRPF"], 1),
        ("¿Cómo tributa el rescate del plan?",
         ["Como donación", "Como rendimientos del trabajo (IRPF)", "Exento siempre", "Solo IVA"], 1),
        ("¿Por qué no usar plan como fondo emergencia?",
         ["Liquidez inmediata", "Pierdes ventajas fiscales y liquidez", "Paga más IVA", "Es obligatorio"], 1),
    ],
    "FOREX y cobertura cambiaria": [
        ("¿Qué par es base/cotizada en EUR/USD?",
         ["USD/EUR", "Euro frente a dólar", "Solo oro", "IBEX/Euríbor"], 1),
        ("¿Qué mueve tipos de cambio?",
         ["Solo turismo", "Tipos de interés, inflación, riesgo geopolítico", "Solo IRPF", "Color del billete"], 1),
        ("Si EUR/USD sube, ¿qué pasa con acciones USA en euros?",
         ["Valen más en euros", "Valen menos en euros si precio USD igual", "No cambia nunca", "Sube IRPF"], 1),
        ("¿Qué riesgo del FOREX retail?",
         ["Apalancamiento y pérdidas rápidas", "Sin riesgo", "Solo ganancias", "Garantía estatal"], 0),
        ("¿Qué es una opción de divisas?",
         ["Obligación de cambiar", "Derecho (no obligación) a tipo acordado", "Préstamo hipotecario", "Plan pensiones"], 1),
        ("¿Qué hacer si viajas y compras fuera UE?",
         ["No comparar", "Comparar tipos (banco vs fintech)", "Solo efectivo caro", "FOREX apalancado"], 1),
        ("¿FOREX especulativo vs cobertura?",
         ["Igual de riesgoso siempre", "Cobertura protege operaciones reales", "Cobertura es apuesta", "Solo empresas especulan"], 1),
    ],
    "Simula una inversión": [
        ("¿Qué activo es recomendable para principiantes en simulación?",
         ["Derivados apalancados", "Acciones IBEX o ETF conocido", "Solo cripto apalancada", "Ninguno"], 1),
        ("¿Qué registrar cada semana en la simulación?",
         ["Solo el clima", "Precio, variación y noticias relevantes", "Nada", "Solo redes sociales"], 1),
        ("¿Qué es análisis técnico básico?",
         ["Solo rumores", "Observar tendencias de precio", "Ignorar datos", "Solo fundamental"], 1),
        ("¿Qué error evita la simulación?",
         ["Aprender disciplina", "Vender en pánico sin experiencia previa", "Investigar", "Documentar"], 1),
        ("¿Tratar la simulación como dinero real implica...?",
         ["Hacer trampas", "Decisiones serias y honestas", "No anotar nada", "Solo ganar"], 1),
        ("¿Qué lección da la volatilidad semanal?",
         ["Precios estables siempre", "Suben y bajan con frecuencia", "Solo suben", "Sin noticias"], 1),
        ("Después del mes, ¿qué reflexionar?",
         ["Solo suerte", "Si fuiste racional o emocional", "Nada", "Culpar al mercado"], 1),
    ],
    "¿Qué es un presupuesto?": [
        ("¿Qué incluir en ingresos del presupuesto?",
         ["Solo nómina si hay más fuentes", "Nómina, ayudas, alquileres, etc.", "Solo efectivo", "Solo bonus"], 1),
        ("¿Qué gasto olvidan a menudo las familias?",
         ["Alquiler mensual", "Gastos anuales o trimestrales", "Comida básica", "Transporte fijo"], 1),
        ("¿Qué herramienta categoriza gastos en bancos españoles?",
         ["Solo papel", "App del banco o apps como Fintonic", "Solo lotería", "Ninguna"], 1),
        ("¿Por qué involucrar a la familia?",
         ["Para gastar más", "Conciencia y colaboración en ahorro", "Evitar IRPF", "Obligación legal"], 1),
        ("¿Qué es flujo de caja negativo?",
         ["Gastas más de lo que ingresas", "Ahorras mucho", "Sin deudas", "Sin gastos"], 0),
        ("¿Qué categoría es gasto fijo?",
         ["Restaurante ocasional", "Alquiler o hipoteca", "Ropa impulsiva", "Capricho"], 1),
        ("¿Beneficio de control mensual?",
         ["Sorpresas a final de mes", "Anticipar y planificar", "Más deudas", "Menos transparencia"], 1),
    ],
    "Registra tus gastos": [
        ("¿Qué método ayuda a no olvidar gastos?",
         ["Registrar semanalmente o diariamente", "Solo memoria", "Una vez al año", "Nunca"], 0),
        ("¿Qué ventaja de categorizar gastos?",
         ["Gastar más", "Ver patrones y negociar tarifas", "Evitar IRPF", "Subir nómina"], 1),
        ("¿Qué error al registrar?",
         ["Ser honesto", "No apuntar compras capricho", "Usar app", "Revisar extractos"], 1),
        ("¿Cuánto pueden sumar gastos hormiga al año?",
         ["Siempre menos de 10€", "Más de 500€ en muchos casos", "Cero", "Solo millonarios"], 1),
        ("¿Qué guardar además de tickets?",
         ["Solo fotos", "Movimientos bancarios", "Nada", "Solo efectivo"], 1),
        ("¿Por qué negociar tarifas tras registrar?",
         ["No sirve", "Detectas gastos altos recurrentes", "Sube IRPF", "Es ilegal"], 1),
        ("¿Hábito comparable a registrar gastos?",
         ["Como lavarse los dientes: constancia", "Solo una vez", "Nunca", "Solo en crisis"], 0),
    ],
    "Prioriza necesidades": [
        ("¿Qué es una necesidad básica?",
         ["Último móvil", "Vivienda y alimentación", "Viaje de lujo", "Ropa de marca"], 1),
        ("¿Qué error al justificar deseos?",
         ["'Necesito el último móvil para trabajar' sin ser cierto", "Priorizar alquiler", "Pagar suministros", "Salud básica"], 0),
        ("En crisis económica, ¿qué priorizar?",
         ["Deseos primero", "Necesidades para estabilidad", "Solo ocio", "Deudas nuevas"], 1),
        ("¿Qué técnica ayuda a priorizar?",
         ["Lista necesidades vs deseos", "Comprar primero deseos", "Ignorar lista", "Solo tarjeta"], 0),
        ("¿Beneficio de cubrir necesidades primero?",
         ["Más estrés", "Tranquilidad y libertad para deseos después", "Más deuda", "Menos ahorro siempre"], 1),
        ("¿Transporte al trabajo es...?",
         ["Siempre deseo", "Generalmente necesidad", "Siempre lujo", "Impuesto"], 1),
        ("Si recortas, ¿por dónde empezar?",
         ["Alquiler", "Deseos y gastos discrecionales", "Medicamentos", "Comida básica"], 1),
    ],
    "Ajusta tu presupuesto": [
        ("¿Qué evento exige ajustar presupuesto?",
         ["Nada", "Paga extra, devolución Hacienda, imprevistos", "Solo lunes", "Cambio de estación irrelevante"], 1),
        ("Si gastaste de más, ¿qué hacer?",
         ["Repetir igual", "Analizar causa y corregir mes siguiente", "Ignorar", "Pedir crédito siempre"], 1),
        ("¿Qué son gastos de Navidad o vuelta al cole?",
         ["Fijos mensuales", "Estacionales previsibles", "Ingresos", "Impuestos"], 1),
        ("¿Herramienta para ver tendencias?",
         ["Solo calculadora", "Gráficos en app bancaria", "Nada", "Lotería"], 1),
        ("¿Qué mantener al ajustar?",
         ["Olvidar objetivos largo plazo", "Vista en metas a largo plazo", "Gastar todo", "Sin revisión"], 1),
        ("¿Reunión familiar mensual sirve para...?",
         ["Gastar más", "Revisar presupuesto conjunto", "Evitar ahorro", "Solo ocio"], 1),
        ("¿Flexibilidad en presupuesto implica...?",
         ["Abandonar metas", "Adaptarse sin perder objetivos", "No registrar", "Más deuda siempre"], 1),
    ],
    "Crea tu presupuesto": [
        ("¿Qué paso tras clasificar necesidades/deseos?",
         ["Ignorar", "Buscar gasto reducible y fijar ahorro", "Pedir préstamo", "Solo invertir"], 1),
        ("¿Por qué compartir presupuesto con alguien de confianza?",
         ["Presumir", "Feedback y motivación", "Evitar IRPF", "Obligación"], 1),
        ("¿Objetivo de ahorro mensual aunque sea pequeño?",
         ["No necesario", "Sí, crear hábito", "Solo millonarios", "Solo jubilados"], 1),
        ("¿Error de ser irrealista?",
         ["Subestimar gastos o sobreestimar ingresos", "Usar hoja cálculo", "Revisar", "Involucrar familia"], 0),
        ("¿Duración mínima para anotar ingresos/gastos inicial?",
         ["Un mes de seguimiento", "Un día", "Diez años", "Nunca"], 0),
        ("¿Plantillas bancarias ayudan a...?",
         ["Gastar más", "Estructurar el presupuesto", "Evitar impuestos", "Solo empresas"], 1),
        ("Tras crear presupuesto, ¿qué evitar?",
         ["Revisarlo", "No revisarlo nunca", "Ajustar", "Registrar"], 1),
    ],
    "¿Qué es emprender?": [
        ("¿Qué barrera cultural menciona España?",
         ["Exceso apoyo", "Miedo al fracaso y trámites", "Sin autónomos", "Sin bancos"], 1),
        ("¿Qué financiación pública existe?",
         ["Ninguna", "ENISA, ICO, ayudas autonómicas", "Solo lotería", "Solo IRPF"], 1),
        ("¿Por qué separar finanzas personales y negocio?",
         ["No es necesario", "Claridad y control fiscal", "Evitar clientes", "Subir IVA"], 1),
        ("¿Qué incluye dar de alta actividad?",
         ["Solo Instagram", "Hacienda y Seguridad Social", "Solo banco", "Nada"], 1),
        ("¿Error al emprender?",
         ["Validar idea", "No calcular cuota autónomos e impuestos", "Plan de negocio", "Asesoramiento"], 1),
        ("¿Ventaja de ser tu propio jefe?",
         ["Sin riesgos", "Decisiones propias y flexibilidad", "Sin impuestos", "Salario fijo garantizado"], 1),
        ("¿Dónde buscar asesoramiento?",
         ["Solo redes", "Cámaras de comercio y bancos", "Ningún sitio", "Solo amigos"], 1),
    ],
    "Detecta oportunidades": [
        ("¿Qué tendencia social en España?",
         ["Sin digitalización", "Envejecimiento, sostenibilidad, digitalización", "Sin turismo", "Sin servicios"], 1),
        ("¿Cómo validar idea?",
         ["Lanzar sin prueba", "Encuestas y prototipos con clientes", "Solo intuición", "Copiar sin adaptar"], 1),
        ("¿Error al emprender por moda?",
         ["Analizar demanda real", "Entrar sin demanda", "Observar mercado", "Escuchar clientes"], 1),
        ("¿Qué preguntar a clientes potenciales?",
         ["Solo precio", "Problemas y necesidades no resueltas", "Color favorito", "Nada"], 1),
        ("¿Adaptar idea al contexto local implica...?",
         ["Ignorar legislación", "Idioma, cultura y normativa local", "Solo copiar extranjero", "Sin competencia"], 1),
        ("¿Ejemplo oportunidad por cambio social?",
         ["Servicios para mayores", "Vender solo CDs", "Ignorar digital", "Sin análisis"], 0),
        ("¿Analizar competencia para...?",
         ["Copiar mal", "Ver qué mejorar", "Ignorar mercado", "Subir precios sin valor"], 1),
    ],
    "Plan de negocio": [
        ("¿Para qué piden bancos un plan de negocio?",
         ["Decoración", "Evaluar financiación y viabilidad", "Solo marketing", "Evitar impuestos"], 1),
        ("¿Qué incluye plan de operaciones?",
         ["Solo logo", "Recursos humanos, proveedores, logística", "Solo Instagram", "Nada"], 1),
        ("¿Qué sección analiza clientes y competencia?",
         ["Análisis de mercado", "Solo portada", "Solo CV", "Anexo fotos"], 0),
        ("¿Error con cifras del plan?",
         ["Ser realista", "Sobreestimar ingresos", "Incluir gastos", "Riesgos"], 1),
        ("¿Plan de contingencia sirve para...?",
         ["Ignorar problemas", "Anticipar riesgos", "Gastar más", "Solo impresionar"], 1),
        ("¿Feedback de mentores ayuda a...?",
         ["Empeorar plan", "Refinar estrategia", "Evitar clientes", "No pagar impuestos"], 1),
        ("¿Plan de negocio es...?",
         ["Solo trámite olvidable", "Hoja de ruta viva del proyecto", "Solo para Instagram", "Opcional siempre"], 1),
    ],
    "Aprende de los errores": [
        ("¿Qué hacer tras un error empresarial?",
         ["Ocultarlo", "Analizar qué salió mal y mejorar", "Culpar solo al mercado", "Repetir igual"], 1),
        ("¿Por qué no castigarse excesivamente?",
         ["Enfocarse en solución", "Ignorar aprendizaje", "Cerrar siempre", "No cambiar"], 0),
        ("¿Red de apoyo incluye...?",
         ["Solo competencia", "Emprendedores, mentores, asociaciones", "Nadie", "Solo Hacienda"], 1),
        ("¿Fracaso es...?",
         ["Siempre el final", "Oportunidad de aprender", "Vergüenza sin valor", "Evitar emprender"], 1),
        ("¿Compartir errores en red ayuda a...?",
         ["Competir mal", "Aprendizaje colectivo", "Evitar clientes", "Subir impuestos"], 1),
        ("¿Grandes emprendedores...?",
         ["Nunca fallan", "Han fracasado antes de triunfar", "Sin errores", "Solo suerte"], 1),
        ("¿Cambiar tras fracaso implica...?",
         ["Repetir exactamente igual", "Ajustar estrategia con aprendizaje", "Abandonar siempre", "Ignorar feedback"], 1),
    ],
    "Crea tu pitch": [
        ("¿Qué incluir en pitch efectivo?",
         ["Solo logo", "Problema, solución, equipo, modelo", "Solo precio", "Currículum largo"], 1),
        ("¿Llamada a la acción al final?",
         ["No necesaria", "Invertir, colaborar o probar producto", "Solo despedida", "Silencio"], 1),
        ("¿Adaptar pitch según audiencia?",
         ["Siempre igual", "Sí, inversores vs clientes", "Solo en inglés", "Sin datos"], 1),
        ("¿Error común en pitch?",
         ["Datos concretos", "Mucha idea, poco mercado/equipo", "Practicar", "Pasión"], 1),
        ("¿Practicar pitch hasta...?",
         ["No practicar", "Dominarlo en ~1 minuto", "Solo leer", "30 minutos mínimo"], 1),
        ("¿Ejemplos y datos concretos...?",
         ["Confunden", "Dan credibilidad", "Sobran", "Solo en plan largo"], 1),
        ("¿Un buen pitch transmite...?",
         ["Solo tecnología", "Visión clara y convincente", "Solo redes", "Miedo"], 1),
    ],
    "Deuda buena vs mala": [
        ("¿Ejemplo de deuda mala?",
         ["Hipoteca vivienda habitual", "Préstamo rápido para vacaciones", "Préstamo estudios", "Financiación negocio rentable"], 1),
        ("¿Qué es TAE?",
         ["Tipo sin comisiones", "Coste total anual incluyendo comisiones", "Solo Euríbor", "Impuesto"], 1),
        ("¿Deuda buena suele tener...?",
         ["Intereses altísimos", "Intereses más bajos y valor futuro", "Plazo 1 día", "Sin contrato"], 1),
        ("¿Error con deudas?",
         ["Comparar condiciones", "Pedir préstamo para pagar otro sin plan", "Leer contrato", "Calcular ratio"], 1),
        ("¿Financiar coche de lujo innecesario es...?",
         ["Deuda buena", "Deuda mala típica", "Inversión", "Sin intereses"], 1),
        ("¿Tarjeta a plazos para consumo suele ser...?",
         ["Deuda buena", "Deuda mala", "Ahorro", "Inversión"], 1),
        ("¿Herramienta para comparar préstamos?",
         ["Simuladores bancarios online", "Solo publicidad", "Lotería", "Ninguna"], 0),
    ],
    "Método bola de nieve": [
        ("¿Alternativa que prioriza interés alto?",
         ["Bola de nieve", "Avalancha (mayor interés primero)", "Ignorar deudas", "Solo mínimos siempre"], 1),
        ("¿Qué hacer al liquidar primera deuda?",
         ["Gastar cuota liberada", "Atacar siguiente deuda pequeña", "Pedir más crédito", "Parar pagos"], 1),
        ("¿Orden típico de lista bola de nieve?",
         ["Mayor a menor", "Menor a mayor importe pendiente", "Alfabético", "Aleatorio"], 1),
        ("¿Error durante el método?",
         ["Seguir usando tarjetas", "Programar pagos automáticos", "Ajustar presupuesto", "Lista de deudas"], 0),
        ("¿Ventaja psicológica?",
         ["Victorias rápidas al eliminar deudas", "Menos motivación", "Más deudas", "Sin orden"], 0),
        ("¿Asociaciones de ayuda?",
         ["ADICAE, OCU", "Solo bancos centrales", "Ninguna", "Solo lotería"], 0),
        ("¿Pagos automáticos ayudan a...?",
         ["Olvidar cuotas", "No olvidar cuotas mínimas", "Subir intereses", "Evitar pagar"], 1),
    ],
    "Historial crediticio": [
        ("¿Qué perjudica historial?",
         ["Pagar a tiempo", "Impagos y retrasos", "Una cuenta", "Ahorrar"], 1),
        ("¿CIRBE registra...?",
         ["Solo depósitos", "Préstamos y riesgos con bancos", "Vacaciones", "IVA"], 1),
        ("¿Mejor historial permite...?",
         ["Peores condiciones", "Mejores tipos y más crédito", "Sin hipoteca", "Evitar IRPF"], 1),
        ("¿Error grave?",
         ["Consultar historial", "Pedir préstamos a nombre ajeno", "Pagar puntual", "Negociar"], 1),
        ("¿ASNEF es...?",
         ["Fichero de morosos", "Tipo de hipoteca", "Plan pensiones", "IVA"], 0),
        ("¿Hablar con banco antes de impago...?",
         ["Inútil", "Puede evitar agraviar situación", "Ilegal", "Solo después de embargo"], 1),
        ("¿Abuso de crédito rápido...?",
         ["Mejora historial", "Lo deteriora", "Sin efecto", "Sube nómina"], 1),
    ],
    "Evita el sobreendeudamiento": [
        ("¿Qué es efecto bola de nieve de deudas?",
         ["Ahorro creciente", "Pedir crédito para pagar crédito", "Inversión", "Plan pensiones"], 1),
        ("¿Ratio de endeudamiento mide...?",
         ["Solo hipoteca", "Cuotas de deuda vs ingresos netos", "Solo tarjetas", "Patrimonio"], 1),
        ("¿Consecuencia grave del sobreendeudamiento?",
         ["Más ahorro", "Embargos y ficheros morosos", "Mejor crédito", "Subida salarial"], 1),
        ("¿Fondo emergencia evita...?",
         ["Todo", "Recurrir al crédito por imprevistos", "IRPF", "IVA"], 1),
        ("¿Dónde acudir si hay problemas?",
         ["Ignorar", "Banco y asociaciones como ADICAE", "Más préstamos", "Solo redes"], 1),
        ("¿Comparar ofertas antes de endeudarse?",
         ["No importa", "Sí, evita condiciones abusivas", "Solo la primera", "Solo publicidad"], 1),
        ("¿Señal de alerta?",
         ["Cuotas >35-40% ingresos", "Ahorro alto", "Sin deudas", "Pago puntual"], 0),
    ],
    "Auditoría de deudas": [
        ("¿Primer paso de auditoría?",
         ["Pedir más crédito", "Listar todas las deudas con detalle", "Ignorar pequeñas", "Cerrar cuentas"], 1),
        ("¿Deudas pequeñas olvidadas?",
         ["No importan", "Sí, incluir tarjetas y familiares", "Solo hipoteca", "Ninguna"], 1),
        ("¿Ordenar deudas puede ser por...?",
         ["Color", "Importe, interés o urgencia", "Solo banco", "Azar"], 1),
        ("¿Renegociar condiciones...?",
         ["Imposible", "Posible con banco o reunificación", "Solo Hacienda", "Ilegal"], 1),
        ("¿Herramienta para control?",
         ["Solo memoria", "Hoja de cálculo o app", "Nada", "Lotería"], 1),
        ("¿Calcular coste mensual total sirve para...?",
         ["Gastar más", "Ver carga real de deuda", "Evitar pagar", "Subir intereses"], 1),
        ("¿Revisar contratos evita...?",
         ["Entender condiciones", "Sorpresas con cláusulas", "Pagar", "Todo"], 1),
    ],
    "¿Qué es un seguro?": [
        ("¿Qué es la indemnización?",
         ["Pago de prima", "Compensación por siniestro cubierto", "Franquicia", "Exclusión"], 1),
        ("¿Seguro hogar con hipoteca?",
         ["Opcional siempre", "Suele ser obligatorio", "Prohibido", "Solo vida"], 1),
        ("¿Qué cubre responsabilidad civil en hogar?",
         ["Solo robo", "Daños a terceros", "Vacaciones", "Nómina"], 1),
        ("¿Error al contratar?",
         ["Comparar ofertas", "Contratar sin leer exclusiones", "Revisar coberturas", "Actualizar capitales"], 1),
        ("¿Seguro de coche mínimo legal?",
         ["Todo riesgo", "Responsabilidad civil (terceros)", "Vida", "Hogar"], 1),
        ("¿Actualizar capitales asegurados?",
         ["Innecesario", "Importante con el tiempo", "Ilegal", "Solo una vez"], 1),
        ("¿Sistema público en España cubre...?",
         ["Todo sin límites", "Mucho pero no todo (ej. sanidad con listas)", "Nada", "Solo empresas"], 1),
    ],
    "Seguro de salud": [
        ("¿Limitación sanidad pública?",
         ["Sin médicos", "Listas de espera en algunos casos", "Gratuita siempre instantánea", "Sin hospitales"], 1),
        ("¿Periodo de carencia?",
         ["Pago extra", "Tiempo antes de cubrir ciertos servicios", "Prima anual", "Franquicia"], 1),
        ("¿No declarar preexistencias puede...?",
         ["Mejorar precio siempre", "Causar exclusiones o anulación", "Obligatorio ocultar", "Subir nómina"], 1),
        ("¿Servicio no siempre público?",
         ["Urgencias", "Fisioterapia o psicología privada", "Médico familia", "Hospital público"], 1),
        ("¿Comparar compañías para...?",
         ["Pagar más", "Ajustar cobertura y precio", "Evitar seguro", "Solo marca"], 1),
        ("¿Seguro salud complementa...?",
         ["Solo ocio", "Sanidad pública", "IRPF", "IVA"], 1),
        ("¿Contratar solo por precio?",
         ["Ideal", "Riesgo de cobertura insuficiente", "Obligatorio", "Sin riesgo"], 1),
    ],
    "Seguro de vida": [
        ("¿Cómo calcular capital necesario?",
         ["Al azar", "Deudas + gastos familiares x años", "Solo 1.000€", "Sin cálculo"], 1),
        ("¿Seguro riesgo puro cubre...?",
         ["Solo ahorro", "Fallecimiento", "Vacaciones", "Coche"], 1),
        ("¿Quién recibe indemnización vida?",
         ["Aseguradora", "Beneficiarios designados", "Banco siempre", "Hacienda"], 1),
        ("¿Actualizar beneficiarios tras divorcio?",
         ["Opcional irrelevante", "Muy importante", "Prohibido", "Automático"], 1),
        ("¿Seguro vida útil con hipoteca?",
         ["Nunca", "Para cubrir deuda si faltas", "Solo solteros", "Obligatorio siempre"], 1),
        ("¿Capital insuficiente implica...?",
         ["Protección completa", "Familia con menos respaldo", "Sin prima", "Más cobertura"], 1),
        ("¿Simuladores online ayudan a...?",
         ["Evitar seguro", "Estimar capital adecuado", "Subir IRPF", "No pagar"], 1),
    ],
    "Compara seguros": [
        ("¿Qué comparar además de precio?",
         ["Solo color póliza", "Coberturas, límites y franquicias", "Nada más", "Solo marca"], 1),
        ("¿Límite de indemnización es...?",
         ["Prima", "Máximo que paga aseguradora", "Franquicia", "Exclusión"], 1),
        ("¿Comparadores online sirven para...?",
         ["Solo publicidad", "Varias ofertas rápidamente", "Evitar seguro", "Solo vida"], 1),
        ("¿Opiniones de clientes ayudan a...?",
         ["Nada", "Evaluar servicio en siniestros", "Subir prima", "Evitar póliza"], 1),
        ("¿Seguro barato sin cobertura...?",
         ["Siempre mejor", "Puede salir caro en siniestro", "Obligatorio", "Sin riesgo"], 1),
        ("¿Preguntar exclusiones implica...?",
         ["Saber qué NO cubre", "Solo marketing", "Subir IRPF", "Cancelar seguro"], 0),
        ("¿Atención al cliente importa en...?",
         ["Solo compra", "Gestión de siniestros", "Nunca", "Solo coche"], 1),
    ],
    "Revisa tus pólizas": [
        ("¿Qué cambio vital exige revisar seguros?",
         ["Nada", "Nacimiento hijo, mudanza, coche nuevo", "Solo cumpleaños", "Cambio estación"], 1),
        ("¿Renovación anual puede traer...?",
         ["Siempre mismo precio", "Cambio de prima o condiciones", "Sin contrato", "Cancelación auto"], 1),
        ("¿Pagar coberturas que no necesitas...?",
         ["Ahorro", "Gasto innecesario", "Obligatorio", "Mejor protección siempre"], 1),
        ("¿Lista de todos los seguros ayuda a...?",
         ["Olvidar", "Visión global de protección", "Gastar más", "Evitar comparar"], 1),
        ("¿Contactar aseguradora sirve para...?",
         ["Solo quejas", "Actualizar datos y dudas", "Subir IRPF", "Cancelar todo"], 1),
        ("¿Marcar fecha anual en calendario...?",
         ["Inútil", "Recordatorio de revisión", "Solo empresas", "Ilegal"], 1),
        ("¿Descubrir tarde mala cobertura...?",
         ["Sin problema", "Sorpresa grave en siniestro", "Mejor", "Obligatorio"], 1),
    ],
    "Establece metas financieras": [
        ("¿Qué significa la M en SMART?",
         ["Medible (con cifra)", "Mensual siempre", "Mínimo", "Máximo"], 0),
        ("¿Meta corto plazo ejemplo?",
         ["Jubilación", "Fondo emergencia o vacaciones <1 año", "Independencia 20 años", "Herencia"], 1),
        ("¿Meta alcanzable implica...?",
         ["Imposible siempre", "Realista con tus ingresos", "Sin fecha", "Sin cifra"], 1),
        ("¿Escribir metas y visible ayuda a...?",
         ["Olvidar", "Mantener enfoque", "Gastar más", "Evitar ahorro"], 1),
        ("¿Subcuentas por objetivo en bancos...?",
         ["No existen", "Facilitan seguimiento (ING, Openbank)", "Solo empresas", "Ilegal"], 1),
        ("¿Meta sin fecha límite suele...?",
         ["Cumplirse sola", "Postergarse indefinidamente", "Ser SMART", "Ahorrar más"], 1),
        ("¿3.000€ en 12 meses requiere...?",
         ["100€/mes", "250€/mes", "500€/mes", "50€/mes"], 1),
    ],
    "Corto, medio y largo plazo": [
        ("¿Riesgo de solo corto plazo?",
         ["Mucha riqueza futura", "No acumular patrimonio", "Mejor jubilación", "Sin gastos"], 1),
        ("¿Riesgo de solo largo plazo?",
         ["Sin motivación y necesidades actuales", "Demasiado ahorro", "Sin inversiones", "Mejor liquidez"], 0),
        ("¿40% ahorro mensual a corto en ejemplo?",
         ["40% del ahorro total", "40% del salario bruto", "40€ fijos", "Nada"], 0),
        ("¿Producto medio plazo?",
         ["Efectivo casa", "Fondos conservadores", "Solo lotería", "Cuenta sin interés"], 1),
        ("¿Revisar distribución cada año...?",
         ["Innecesario", "Ajustar a situación vital", "Solo una vez", "Prohibido"], 1),
        ("¿300€ ahorro, 30% largo plazo = ?",
         ["30€", "90€", "120€", "150€"], 1),
        ("¿Equilibrio tres horizontes es...?",
         ["Complicar sin sentido", "Base de planificación sana", "Solo bancos", "Solo ricos"], 1),
    ],
    "Crea tu plan financiero": [
        ("¿Qué son pasivos en el plan?",
         ["Lo que tienes", "Lo que debes (deudas)", "Solo ingresos", "Solo gastos ocio"], 1),
        ("¿Flujo de caja positivo significa...?",
         ["Gastas más", "Ingresos superan gastos", "Sin deuda", "Sin activos"], 1),
        ("¿Balance neto negativo indica...?",
         ["Debes más de lo que tienes", "Riqueza total", "Sin acción", "Solo IRPF"], 0),
        ("¿Priorizar metas por...?",
         ["Color", "Urgencia e importancia", "Azar", "Solo ocio"], 1),
        ("¿Plan sencillo actualizado vs perfecto olvidado?",
         ["Perfecto olvidado mejor", "Sencillo y usado vale más", "Ninguno sirve", "Solo papel"], 1),
        ("¿Inventario incluye...?",
         ["Solo deudas", "Activos e inversiones también", "Solo ocio", "Nada"], 1),
        ("¿Seguimiento cada 3-6 meses...?",
         ["Excesivo", "Recomendado", "Nunca", "Solo jubilación"], 1),
    ],
    "Revisa y ajusta tu plan": [
        ("¿Cita financiera mensual dura...?",
         ["5 horas", "~30 minutos", "1 semana", "0 minutos"], 1),
        ("¿Al alcanzar meta, qué hacer?",
         ["Parar planificar", "Celebrar y fijar siguiente meta", "Gastar todo", "Ignorar"], 1),
        ("¿2 meses sin ahorrar es...?",
         ["Normal siempre", "Señal de alerta", "Obligatorio", "Meta SMART"], 1),
        ("¿Deudas >10% interés son...?",
         ["Prioridad reducir", "Ignorar", "Buenas siempre", "Sin coste"], 0),
        ("¿Cambio de trabajo exige...?",
         ["Ignorar plan", "Revisar ingresos y plan", "Solo vacaciones", "Cerrar cuentas"], 1),
        ("¿Rendimiento inversión bajo esperado...?",
         ["Nunca revisar", "Revisar estrategia", "Retirar todo impulsivo", "Sin plan"], 1),
        ("¿Metas pueden cambiar con...?",
         ["Nunca", "Matrimonio, hijos, herencia, etc.", "Solo edad", "Solo banco"], 1),
    ],
    "Simula tu futuro financiero": [
        ("¿200€/mes 30 años al 6% ≈ total aportado?",
         ["48.000€", "72.000€", "201.000€", "20.000€"], 1),
        ("¿Esperar 10 años menos a invertir implica...?",
         ["Mismo resultado", "Perder gran parte del interés compuesto", "Más capital", "Menos riesgo solo"], 1),
        ("¿Herramienta simular en España?",
         ["Solo papel", "Rankia, simuladores fondos", "Lotería", "Ninguna"], 1),
        ("¿50€/mes a los 25 vs 200€ a los 45?",
         ["Igual siempre", "Empezar joven compensa tiempo", "Mejor esperar", "Sin diferencia"], 1),
        ("¿Interés compuesto en simulación...?",
         ["Solo capital inicial", "Aportaciones + rendimientos reinvertidos", "Solo impuestos", "Solo IVA"], 1),
        ("¿201.000€ en ejemplo incluye...?",
         ["Solo aportaciones", "Aportaciones + rendimientos", "Solo suerte", "Solo IRPF devuelto"], 1),
        ("¿Conclusión principal del desafío?",
         ["Esperar siempre", "Empezar hoy aunque sea poco", "Solo grandes sumas", "No invertir"], 1),
    ],
    "¿Por qué gastamos más de la cuenta?": [
        ("¿Gratificación inmediata implica...?",
         ["Preferir recompensa ahora vs después", "Más ahorro", "Sin compras", "Solo inversiones"], 0),
        ("¿Cuánto más se gasta con tarjeta vs efectivo (estudios)?",
         ["Menos", "Hasta ~83% más", "Igual siempre", "0%"], 1),
        ("¿Comparación social en redes...?",
         ["Reduce gasto", "Presión de consumo innecesaria", "Sin efecto", "Solo ahorro"], 1),
        ("¿Gasto emocional crea...?",
         ["Círculo vicioso", "Riqueza automática", "Menos deuda", "Más IRPF"], 0),
        ("¿Dolor de pagar menor con móvil/tarjeta...?",
         ["Gastas más fácilmente", "Gastas menos", "Sin efecto", "Solo efectivo"], 0),
        ("¿Pregunta antes de comprar no esencial?",
         ["¿Lo necesito o solo quiero ahora?", "¿Es la marca más cara?", "¿Puedo endeudarme?", "¿Lo compra mi vecino?"], 0),
        ("¿Problemas financieros son a menudo...?",
         ["Solo matemáticos", "Psicológicos y emocionales", "Solo legales", "Sin solución"], 1),
    ],
    "Sesgos cognitivos y dinero": [
        ("¿Sesgo confirmación implica...?",
         ["Buscar info que confirma creencias", "Diversificar", "Automatizar", "Plan escrito"], 0),
        ("¿Exceso de confianza lleva a...?",
         ["Mejor que índice", "Peores resultados que fondo indexado", "Sin riesgo", "Más diversificación"], 1),
        ("¿Política inversión escrita ayuda a...?",
         ["Improvisar", "Seguir reglas y evitar impulsos", "Especular más", "Ignorar mercado"], 1),
        ("¿Sesgo presente valoriza...?",
         ["Futuro sobre presente", "Presente sobre futuro", "Solo ahorro", "Solo deuda"], 1),
        ("¿Combatir sesgos con automatización...?",
         ["Empeora", "Reduce decisiones impulsivas", "Sin efecto", "Solo ricos"], 1),
        ("¿Buffett recomienda opuesto a manada...?",
         ["Comprar en euforia", "Ser cauteloso cuando otros codiciosos", "Seguir modas", "Vender nunca"], 1),
        ("¿Mantener inversión perdedora por aversión...?",
         ["Siempre racional", "Sesgo común a evitar", "Obligatorio", "Mejor estrategia"], 1),
    ],
    "El coste emocional del dinero": [
        ("¿Estrés financiero afecta...?",
         ["Solo bolsillo", "Salud, sueño y decisiones", "Solo impuestos", "Nada"], 1),
        ("¿Círculo vicioso del estrés?",
         ["Poco dinero → estrés → malas decisiones", "Ahorro → estrés", "Inversión → paz", "Deuda → riqueza"], 0),
        ("¿Transparencia sobre situación...?",
         ["Empeora", "Reduce autoengaño y ansiedad", "Inútil", "Ilegal"], 1),
        ("¿Plan pequeño de acción...?",
         ["Inútil", "Reduce ansiedad", "Solo deuda", "Sin efecto"], 1),
        ("¿Red de apoyo incluye OCU/ADICAE...?",
         ["Sí", "No existen", "Solo bancos privados", "Nadie"], 0),
        ("¿Desconexión digital si presiona gasto...?",
         ["Mala idea", "Puede ayudar", "Obligatorio", "Sin efecto"], 1),
        ("¿Hablar de dinero en pareja...?",
         ["Evitar siempre", "Mejora comunicación y conflictos", "Ilegal", "Sin beneficio"], 1),
    ],
    "Cómo mejorar tu disciplina financiera": [
        ("¿Disciplina financiera es más...?",
         ["Solo fuerza voluntad", "Diseño de entorno", "Suerte", "IRPF"], 1),
        ("¿Fraccionar meta 10.000€ en...?",
         ["Un solo año imposible", "Metas mensuales manejables", "Ignorar", "Deuda"], 1),
        ("¿Regla 24h para compras >50€...?",
         ["Comprar más", "80% veces no comprarás", "Obligatorio legal", "Sin efecto"], 1),
        ("¿Cuenta ahorro difícil acceso...?",
         ["Gastar más fácil", "Menos tentación de tocar ahorro", "Sin ahorro", "Más deuda"], 1),
        ("¿Recompensas al cumplir metas...?",
         ["Malas siempre", "Refuerzo positivo útil", "Prohibidas", "Sin efecto"], 1),
        ("¿Un cambio de hábito 30 días...?",
         ["Cambiar todo a la vez", "Empezar con uno solo", "Ninguno", "Solo en enero"], 1),
        ("¿Automatizar día de cobro...?",
         ["Si dinero no pasa por manos, menos gasto", "Gastar antes", "Sin ahorro", "Más impuestos"], 0),
    ],
    "Diseña tus hábitos financieros": [
        ("¿Señal en ciclo hábito ahorro?",
         ["Llega la nómina", "Gastar todo", "Dormir", "IVA"], 0),
        ("¿Registro gastos 30 días sirve para...?",
         ["Gastar más", "Conocer patrones", "Evitar banco", "Subir IRPF"], 1),
        ("¿Contenido financiero 15 min/día...?",
         ["Pérdida tiempo", "Educación continua", "Solo expertos", "Prohibido"], 1),
        ("¿Competidor en finanzas personales?",
         ["Tu vecino", "Tú de hace un año", "Solo el banco", "Nadie"], 1),
        ("¿Recompensa en ciclo hábito?",
         ["Ver saldo crecer y seguridad", "Gastar deuda", "Multa", "IRPF"], 0),
        ("¿Libro recomendado español?",
         ["La psicología del dinero", "Solo novela", "Ninguno", "Solo tabloides"], 0),
        ("¿Implementar un hábito 30 días antes del siguiente...?",
         ["Todos a la vez", "Automatizar uno primero", "Nunca", "Solo cinco"], 1),
    ],
    "¿Comprar o alquilar?": [
        ("¿Ventaja comprar frente inflación alquiler?",
         ["Siempre peor", "Protección patrimonial", "Sin costes", "Más flexibilidad"], 1),
        ("¿Alquilar libera capital para...?",
         ["Solo ocio", "Invertir en otros activos", "Pagar IVA", "Nada"], 1),
        ("¿Esfuerzo vivienda/salario en España...?",
         ["Bajo en Europa", "Entre los más altos", "Sin datos", "Cero"], 1),
        ("¿En Madrid/BCN a corto plazo...?",
         ["Alquilar puede ser más barato", "Comprar siempre más barato", "Igual siempre", "Sin vivienda"], 0),
        ("¿Estabilidad laboral dudosa favorece...?",
         ["Comprar ya", "Alquilar más prudente", "Dos hipotecas", "Sin plan"], 1),
        ("¿Gastos mantenimiento propietario...?",
         ["Los paga inquilino siempre", "IBI, comunidad, reparaciones", "Ninguno", "Solo inquilino"], 1),
        ("¿Regla 5-7 años para comprar...?",
         ["Permanencia mínima razonable", "Comprar por 1 mes", "Solo extranjeros", "Ley obligatoria"], 0),
    ],
    "Cómo funciona la hipoteca": [
        ("¿Capital hipotecado típico?",
         ["100% siempre", "Hasta ~80% valor tasación", "50% máximo", "200%"], 1),
        ("¿Hipoteca variable referencia...?",
         ["IBI", "Euríbor + diferencial", "IVA", "IRPF"], 1),
        ("¿Euríbor alto en 2023-24 implicó...?",
         ["Cuotas más bajas", "Cuotas más altas para muchos", "Sin cambio", "Sin hipotecas"], 1),
        ("¿TIN vs TAE?",
         ["TAE incluye más costes", "TIN siempre mayor", "Iguales", "TAE sin comisiones"], 0),
        ("¿Vivienda nueva lleva...?",
         ["Solo ITP", "IVA 10% (general)", "Sin impuestos", "Solo AJD sin IVA"], 1),
        ("¿Garantía en hipoteca?",
         ["Ninguna", "El inmueble", "Solo nómina", "Coche"], 1),
        ("¿Efectivo necesario además del 20%?",
         ["Nada más", "~10% gastos compra aprox.", "50% más", "Solo 5%"], 1),
    ],
    "Gastos ocultos al comprar vivienda": [
        ("¿ITP en vivienda usada varía por...?",
         ["Marca coche", "Comunidad autónoma", "Edad comprador", "Mes"], 1),
        ("¿AJD aplica a...?",
         ["Solo alquiler", "Vivienda nueva (documentos)", "Salario", "Comida"], 1),
        ("¿IBI lo paga...?",
         ["Inquilino siempre", "Propietario anualmente", "Banco", "Hacienda al comprador una vez"], 1),
        ("¿Mantenimiento recomendado reservar...?",
         ["0%", "~1% valor vivienda anual", "50%", "Solo primer mes"], 1),
        ("¿Ejemplo 200.000€ Madrid: ITP ~12.000€ más otros...?",
         ["Total ~15.000€ extras plausible", "Solo 500€", "Cero", "1 millón"], 0),
        ("¿Tasación bancaria cuesta...?",
         ["300-500€ aprox.", "Gratis siempre", "10% precio", "Sin tasación"], 0),
        ("¿Pedir estimación escrita antes firmar...?",
         ["Innecesario", "Evita sorpresas", "Ilegal", "Solo vendedor"], 1),
    ],
    "La vivienda como inversión": [
        ("¿Apalancamiento inmobiliario significa...?",
         ["Comprar 200.000€ con parte propia y crédito", "Sin deuda", "Solo efectivo", "Alquilar siempre"], 0),
        ("¿Yield bruto 5% significa...?",
         ["Alquiler anual / precio compra", "Precio / alquiler", "Solo gastos", "IBI solo"], 0),
        ("¿Concentrar solo en vivienda...?",
         ["Diversificación ideal", "Alto riesgo concentrado", "Sin gestión", "Liquidez alta"], 1),
        ("¿Rentabilidad neta inmobiliaria vs fondo global...?",
         ["Vivienda siempre superior neta", "A menudo fondo global compite mejor", "Igual siempre", "Sin datos"], 1),
        ("¿Inversión alquiler implica...?",
         ["Gestión inquilinos y reparaciones", "Sin trabajo", "Solo cobrar", "Sin impuestos"], 0),
        ("¿Cuándo tiene sentido invertir inmuebles?",
         ["Sin vivienda propia siempre", "Con patrimonio diversificado y conocimiento", "Siempre único activo", "Nunca"], 1),
        ("¿Inflación a largo plazo y vivienda...?",
         ["Protección relativa del activo", "Sin relación", "Siempre pierde", "Solo alquiler"], 0),
    ],
    "Simula tu hipoteca": [
        ("¿Cuota ~880€ ejemplo implica total banco...?",
         ["176.000€", "264.000€ en 25 años", "220.000€", "88.000€"], 1),
        ("¿Amortización anticipada...?",
         ["Prohibida", "Reduce intereses totales", "Sube intereses", "Sin comisión nunca"], 1),
        ("¿Coste real vivienda 220.000€ con intereses...?",
         ["220.000€", "~334.400€ en ejemplo", "176.000€", "88.000€"], 1),
        ("¿Capital propio = entrada + gastos...?",
         ["Sí (~70.400€ en ejemplo)", "Solo hipoteca", "Solo intereses", "Solo ITP"], 0),
        ("¿Simulador Banco de España en...?",
         ["bankofspain.es", "Solo apps juego", "Ningún sitio", "Solo notaría"], 0),
        ("¿Firmar sin calcular coste total...?",
         ["Recomendado", "Error grave", "Obligatorio", "Sin riesgo"], 1),
        ("¿Plazo más corto asumible...?",
         ["Más intereses", "Menos intereses totales", "Sin cuota", "Misma cuota siempre"], 1),
    ],
}


def q_to_dart(question, options, correct_index):
    opts = ", ".join(f"'{o.replace(chr(39), chr(92)+chr(39))}'" for o in options)
    return f"""    PillQuizData(
      question: '{question.replace("'", "\\'")}',
      options: [{opts}],
      correctIndex: {correct_index},
    )"""


def main():
    assert len(PILLS) == 54, f"Expected 54 pills, got {len(PILLS)}"
    for title, qs in PILLS.items():
        assert len(qs) == 7, f"{title}: expected 7 questions, got {len(qs)}"

    lines = [
        "/// Extra PillQuiz questions (7 per pill) for FINANCE4U EduPills.",
        "/// Convert to [PillQuiz] in content_screen.dart.",
        "",
        "class PillQuizData {",
        "  final String question;",
        "  final List<String> options;",
        "  final int correctIndex;",
        "",
        "  const PillQuizData({",
        "    required this.question,",
        "    required this.options,",
        "    required this.correctIndex,",
        "  });",
        "}",
        "",
        "/// Seven additional quiz questions per pill title (54 pills × 7 = 378).",
        "const pillQuizExtras = <String, List<PillQuizData>>{",
    ]

    for title in sorted(PILLS.keys(), key=lambda t: list(PILLS.keys()).index(t)):
        # preserve order as defined in PILLS dict
        pass

    for title, qs in PILLS.items():
        lines.append(f"  '{title.replace(chr(39), chr(92)+chr(39))}': [")
        for q in qs:
            lines.append(q_to_dart(*q) + ",")
        lines.append("  ],")

    lines.extend([
        "};",
        "",
        "/// Returns extra quiz questions for a pill title, or empty list if unknown.",
        "List<PillQuizData> extraQuizzesFor(String pillTitle) {",
        "  return pillQuizExtras[pillTitle] ?? const [];",
        "}",
        "",
    ])

    OUT.write_text("\n".join(lines), encoding="utf-8")
    line_count = len(lines)
    print(f"Wrote {OUT} ({line_count} lines, {sum(len(v) for v in PILLS.values())} questions)")


if __name__ == "__main__":
    main()
